#!/usr/bin/env php
<?php

$readmeContents = @file_get_contents(__DIR__ . '/../README.md');
if (!$readmeContents || empty($readmeContents)) {
    echo 'README.md does not exist or is empty.' . PHP_EOL;
    exit(1);
}
$readmeDocopt = preg_replace('/.*```.(Test-Generator.+?)```.*/s', '$1', $readmeContents);

$appContents = file_get_contents(__DIR__ . '/../bin/test-generator');
if (!$appContents || empty($appContents)) {
    echo 'bin/test-generator does not exist or is empty.' . PHP_EOL;
    exit(1);
}
$appDocopt = preg_replace('/.*<<<EOT.(.+?)EOT;.*/s', '$1', $appContents);

if ($appDocopt !== $readmeDocopt) {
    echo 'Docopt in README.md is not the same as in bin/test-generator.' . PHP_EOL;
    exit(1);
}

exit(0);
