#!/usr/bin/env php
<?php

$readmeContents = file_get_contents(__DIR__ . '/../README.md');
$readmeDocopt = preg_replace('/.*```.(Test-Generator.+?)```.*/s', '$1', $readmeContents);

$appContents = file_get_contents(__DIR__ . '/test-generator');
$appDocopt = preg_replace('/.*<<<EOT.(.+?)EOT;.*/s', '$1', $appContents);

if ($appDocopt !== $readmeDocopt) {
    echo 'Docopt in README.md is not the same as in bin/test-generator.' . PHP_EOL;
    exit(1);
}

exit(0);
