#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use PhpParser\Node;
use PhpParser\Node\Expr\BinaryOp\Coalesce as CoalesceNode;
use PhpParser\Node\Expr\FuncCall;
use PhpParser\Node\Expr\Isset_ as IssetNode;
use PhpParser\Node\Expr\MethodCall;
use PhpParser\Node\Expr\StaticCall;
use PhpParser\Node\Expr\Ternary as TernaryNode;
use PhpParser\Node\Name;
use PhpParser\Node\Stmt\ClassConst;
use PhpParser\Node\Stmt\ClassMethod;
use PhpParser\Node\Stmt\Declare_;
use PhpParser\Node\Stmt\Function_;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitor\NameResolver;
use PhpParser\NodeVisitorAbstract;
use PhpParser\ParserFactory;
use PhpParser\PrettyPrinter;

$description = <<<EOT
PHP7-Type-Declaration-Remover

Usage:
  remove-php7-features <input-file> [<output-file>] [--write]
EOT;

class Php7FeatureRemover extends NodeVisitorAbstract
{
    private static $INVALID_PARAM_TYPES = [
        'bool',
        'int',
        'string',
        'float',
        'boolean',
        'double',
        'iterable',
        'Throwable',
    ];

    public function leaveNode(Node $node) {
        if ($node instanceof ClassMethod || $node instanceof Function_) {
            foreach ($node->params as &$param) {
                if (in_array($param->type->name ?? '', self::$INVALID_PARAM_TYPES, true)) {
                    $param->type = null;
                }
                if ($param->variadic) {
                    $param->variadic = false;
                }
            }
            $node->returnType = null;
        } else if ($node instanceof Declare_
            && $node->declares[0]->key->name ?? '' === 'strict_types')  {
            return NodeTraverser::REMOVE_NODE;
        } else if ($node instanceof ClassConst) {
            $node->flags = 0;
        } else if ($node instanceof CoalesceNode) {
            return $this->convertCoalesceToTernaryWithIsset($node);
        } else if ($node instanceof FuncCall) {
             return $this->replaceSplatOperator($node);
        } else if ($node instanceof StaticCall) {
             return $this->replaceSplatOperator($node);
        } else if ($node instanceof MethodCall) {
             return $this->replaceSplatOperator($node);
        }
        return null;
    }

    /**
     * @TODO
     */
    private function replaceSplatOperator(Node $node): Node
    {
        return $node;
        $callable = [];
        $arguments = [];
        return new FuncCall(
            new Name('call_user_func_array'),
            [$callable, $arguments]
        );

    }

    private function convertCoalesceToTernaryWithIsset(CoalesceNode $coalesceNode): TernaryNode
    {
        return new TernaryNode(
            new IssetNode([$coalesceNode->left]),
            $coalesceNode->left,
            $coalesceNode->right
        );
    }
}

function main(\Docopt\Response $args)
{
    $inputFile = $args['<input-file>'];
    $outputFile = $args['<output-file>'];

    if (!is_file($inputFile)
        || !is_readable($inputFile)
    ) {
        echo 'Input file is not a file or not readable' . PHP_EOL;
        exit(1);
    }

    if ($args['--write']) {
        $outputFile = $inputFile;
    }

    if ($outputFile !== null && !is_writable(dirname($outputFile)))
    {
        echo 'Output file is not writable' . PHP_EOL;
        exit(1);
    }

    $parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
    $traverser = new NodeTraverser;
    $prettyPrinter = new PrettyPrinter\Standard;

    $traverser->addVisitor(new NameResolver);
    $traverser->addVisitor(new Php7FeatureRemover);

    try {
        $code = file_get_contents($inputFile);
        $statements = $traverser->traverse($parser->parse($code));
        $code = $prettyPrinter->prettyPrintFile($statements);

        $outputFile
            ? file_put_contents($outputFile, $code)
            : print($code);
    } catch (PhpParser\Error $e) {
        echo 'Parse Error: ' . $e->getMessage() . PHP_EOL;
        exit(2);
    } catch (Exception $exception) {
        echo 'Something went wrong.' . PHP_EOL;
        exit(3);
    }
}

main(Docopt::handle($description));
